[bans]
multiple-versions = "deny"
skip = [
]
wildcards = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "Unicode-DFS-2016",
    "Zlib",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"
