[bindings.kotlin]
package_name = "com.imageToolkit.core"
generate_immutable_records = true

[bindings.swift]
ffi_module_name = "ImageToolkitCoreFFI"
module_name = "ImageToolkitCore"
generate_immutable_records = true
