[bindings.kotlin]
package_name = "com.imagekit.sdk"
cdylib_name = "imagekit_uniffi"
generate_immutable_records = true

[bindings.swift]
ffi_module_name = "ImagekitFFI"
module_name = "ImagekitSDK"
generate_immutable_records = true
